[package]
name = "raycast-rust-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
inventory = { workspace = true }
futures = "0.3"
thiserror = "1.0"